---
title: "GREGORY practice"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

```{r gregory}
# Example
gregory(y = dat_s$Tree_Height,
        x_sample = dat_s[c("Crown_Width_NS", "DBH", "Condition", "Family")],
        x_pop = dat_x_bar %>% filter(Family == "Pinaceae") %>% select(-Family),
        resolution = "Condition",
        estimation = "Family",
        y_est_name = "Pinaceae",
        prop = dat_prop %>% filter(Family == "Pinaceae") %>% select(-Family))
```

```{r pixel province}
# Initial Wrangle
# need province_proportions
# province_proportions <- read_csv("~/math343_s20_forests/totally legal data/province_proportions.csv")
# need total_data
# total_data <- read_csv("~/math343_s20_forests/data/forKelly_20190206/total_data.csv")
province_proportions_new <- province_proportions %>%
  filter(fips == 49009) %>%
  mutate(prop = percent,
         eco_pro_code = province) %>%
  select(eco_pro_code, prop)

province_proportions <- province_proportions %>%
  rename(eco_pro_code = province)
```

```{r pixel_means}
# auxillary variables pixel level
# pixel_county <- read_csv("~/math343_s20_forests/totally legal data/pixel_county.csv")
pixel_mean <- pixel_county %>% 
  mutate(mean = mean_forbio, 
         variable = "forbio") %>% 
  select(fips, variable, mean)

pixel_county_new <- pixel_county %>%
  rename(forprob = mean_forprob,
         nlcd11 = mean_nlcd11,
         forbio = mean_forbio)
```

```{r}
# wrangle forbio pixel
# iw_subsec_forbio_stats <- read_csv("~/math343_s20_forests/totally legal data/New Pixel Data/iw_subsec_forbio_stats.csv")
pixel_pro_forbio <- iw_subsec_forbio_stats %>%
  mutate(eco_pro_code = substr(zoneid, 1, 3)) %>%
  mutate(total = npixels * mean) %>%
  group_by(eco_pro_code) %>%
  summarize(total_mean = sum(total),
            total_pixels = sum(npixels)) %>% 
  mutate(mean = total_mean/total_pixels, 
         variable = "forbio") %>%
  select(eco_pro_code, variable, mean) 

```
```{r}
province_proportions_new <- province_proportions %>%
  filter(fips == 49009) %>%
  mutate(prop = percent,
         eco_pro_code = province) %>%
  select(eco_pro_code, prop)

gregory(y = total_data$BALIVE_TPA, 
        x_sample =  total_data[c("forbio", "eco_pro_code", "fips")],
        x_pop = pixel_mean %>% filter(fips == 49009) %>% select(-fips),
        resolution = "eco_pro_code",
        estimation = "fips",
        y_est_name = 49009,
        prop = province_proportions_new)
```



```{r, warning = F, message=F}

start.time <- Sys.time()

unique(total_data$fips) %>%
  map_dfr(.f = function(.){
    province_proportions_new <- province_proportions %>%
    filter(fips == .) %>%
    mutate(prop = percent,
           eco_pro_code = province) %>%
    select(eco_pro_code, prop)
    
    result <- gregory(y = total_data$BALIVE_TPA, 
        x_sample =  total_data[c("forbio", "eco_pro_code", "fips")],
        x_pop = pixel_mean %>% filter(fips == .) %>% select(-fips),
        resolution = "eco_pro_code",
        estimation = "fips",
        y_est_name = .,
        prop = province_proportions_new)
    
    return(data.frame(fips = .,
                      estimate = result))
  })
time.taken1 <- end.time - start.time
time.taken1

```