---
title: "work"
output: pdf_document
---


```{r}
#load libraries and set seed
library(mase)
library(pdxTrees)
library(tidyverse)

set.seed(13)
```

```{r}
#load and wrangle data
dat <- get_pdxTrees_parks() %>%
  as.data.frame() %>%
  drop_na(DBH, Crown_Width_NS, Tree_Height) %>%
  filter(Condition != "Dead") %>%
  select(UserID, Tree_Height, Crown_Width_NS, DBH, Condition, Family)


dat_s <- dat %>%
  sample_n(1000) %>%
  as.data.frame()

dat <- dat %>%
  select(-Tree_Height)

dat_est <- dat %>%
  filter(Family == "Pinaceae")
```


```{r}
#mase

est <- greg(y = dat_s$Tree_Height, x_sample =  dat_s[c("Crown_Width_NS", "DBH", "Condition")],
            x_pop = dat[c("Crown_Width_NS", "DBH", "Condition")],
            data_type = "raw")

est$pop_mean

est$pop_mean_var

dat_x_means <- get_pdxTrees_parks() %>%
  as.data.frame() %>%
  drop_na(DBH, Crown_Width_NS, Tree_Height) %>%
  dplyr::summarize(DBH = mean(DBH), Crown_Width_NS = mean(Crown_Width_NS), 
            Tree_Height = mean(Tree_Height))


est <- greg(y = dat_s$Tree_Height, x_sample =  dat_s[ c("Crown_Width_NS", "DBH")],
            x_pop = dat_x_means, var_est = TRUE,
            data_type = "means", N = 25271)
#est
```



```{r}
y_bar_function <- function(y, x_sample, estimation, est_name){
  result_df <- x_sample %>%
    dplyr::filter(.data[[estimation]] == est_name) %>%
    dplyr::select({{ y }}) %>%
    summarize(y_bar = mean({{ y }}))
  
  return(result_df$y_bar[[1]])
}

gregory <- function(y, x_sample, x_pop, x_est, resolution, estimation, est_name,
                        data_type = "raw",
                        prop = NA){
  
  #to keep inputs the same, let's attack y to x_sample
  
  x_sample <- x_sample %>%
    dplyr::mutate(y_column_name = y)
  
  
  predictors <- names(x_pop)[!(names(x_pop) %in% c(resolution, estimation))]
  
  
  #y bar
  
  y_bar <- y_bar_function(y = y_column_name,
                          x_sample = x_sample,
                          estimation = estimation,
                          est_name = est_name)
  
  #check what resolutions are in estimation unit of interest
  #p represents set of resolutions
    p <- unique(x_est[resolution])
    p <- p[[1]]
    
    #filter our plot data to only have data with resolutions of interest
    x_sample <- x_sample %>%
      dplyr::filter(.data[[resolution]] %in% p)
    
    #filter out pixel data to only have data with resolutions of interest
    
    x_pop <- x_pop %>%
      dplyr::filter(.data[[resolution]] %in% p)
    
     x_bar_n <- x_sample %>%
        dplyr::group_by(.data[[resolution]]) %>%
        dplyr::summarize(dplyr::across(predictors,
                                mean)) %>%
        dplyr::mutate("(Intercept)" = 1) %>%
        tidyr::pivot_longer(!.data[[resolution]],
                            names_to = "variable",
                            values_to = "mean") %>%
        dplyr::mutate(term = "n")
      
      print(x_bar_n)
    
    if(data_type == "raw"){
      #because data is raw, we can know the proportion w_l
      w_l <- x_est %>%
        dplyr::group_by(.data[[resolution]]) %>%
        dplyr::summarize(count = n()) %>%
        dplyr::mutate(prop = count / nrow(x_est)) %>%
        dplyr::select(-count)
      
      print(w_l)
      
      #get x_l

      x_bar_N <- x_pop %>%
        dplyr::group_by(.data[[resolution]]) %>%
        dplyr::summarize(dplyr::across(predictors,
                                mean)) %>%
        dplyr::mutate("(Intercept)" = 1) %>%
        tidyr::pivot_longer(!.data[[resolution]],
                            names_to = "variable",
                            values_to = "mean") %>%
        dplyr::mutate(term = "N")
      
      
      print(x_bar_N)
    }
    
    if(data_type == "means"){
      
      w_l = props
      
      x_bar_N = x_pop %>%
        mutate(term = "N")
    }
    
    
    #get betas
    
    
    
    #iterate over p
    betas <- p %>%
      purrr::map_dfr(.f = function(.){
        
        #this is to avoid weird bug
        period_two <- .
        
        x_sample_filtered <- x_sample %>%
          dplyr::filter(.data[[resolution]] == period_two)
        
        model <- lm(as.formula(c(paste("y_column_name", "~"),
                        paste(predictors, collapse = " + "))),
           data = x_sample_filtered)
        
        result <- data.frame(resolution = .,
                             variable = names(model$coefficients),
                             beta = unname(model$coefficients))
        
        names(result)[[1]] <- resolution
        
        return(result)
        
      }) #%>%
      #dplyr::filter(variable != "(Intercept)")
    
    print(betas)
    
    #join n/N with betas
    
    little_n_df <- dplyr::left_join(x_bar_n, betas,
                             by = c(resolution, "variable")) %>%
      group_by(.data[[resolution]]) %>%
      dplyr::summarize(little_n_sum = sum(mean * beta))
    
    big_N_df <- dplyr::left_join(x_bar_N, betas,
                             by = c(resolution, "variable")) %>%
      group_by(.data[[resolution]]) %>%
      dplyr::summarize(big_N_sum = sum(mean * beta))
    
    final_df <- dplyr::left_join(little_n_df, big_N_df, by = resolution) %>%
      dplyr::left_join(w_l) %>%
      dplyr::mutate(almost_final_sum = prop * (-little_n_sum + big_N_sum)) %>%
      dplyr::summarize(result = sum(almost_final_sum))
    
    result = y_bar + final_df$result[[1]]
    
    print(result)
    print(y_bar)
 
                    }



gregory(y = dat_s$Tree_Height, x_sample =  dat_s[c("Crown_Width_NS", "DBH", "Condition", "Family")],
        x_pop = dat[c("Crown_Width_NS", "DBH", "Condition", "Family")],
        x_est = dat_est[c("Crown_Width_NS", "DBH", "Condition", "Family")],
        resolution = "Condition",
        estimation = "Family",
        est_name = "Pinaceae",
        data_type = "raw")
```